import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions);
    console.log("🚀 ~ file: layout.js:17 ~ RootLayout ~ session:", session);
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="navbar">
                    <Link href="/" className="logo">
                        Appleforum
                    </Link>
                    <Link href="/list">List</Link>
                    {session == null ? (
                        <LoginBtn />
                    ) : (
                        <div>
                            <p>{session.user.name}</p>
                            <LogoutBtn />
                        </div>
                    )}
                </div>
                {children}
            </body>
        </html>
    );
}
