import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import LoginBtn from "./LoginBtn";
import LogoutBtn from "./LogoutBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";
import DarkMode from "./DarkMode";
import { cookies } from "next/headers";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    let session = await getServerSession(authOptions);

    let res = cookies().get("mode");
    console.log("🚀 ~ file: layout.js:22 ~ RootLayout ~ res:", res);
    return (
        <html lang="en">
            <body
                className={
                    res != undefined && res.value == "dark" ? "dark-mode" : ""
                }
            >
                <div className="navbar">
                    <Link href="/" className="logo">
                        Appleforum
                    </Link>
                    <Link href="/list">List</Link>
                    {session == null ? (
                        <LoginBtn />
                    ) : (
                        <div>
                            <p>{session.user.name}</p>
                            <LogoutBtn />
                        </div>
                    )}
                    <DarkMode />
                </div>
                {children}
            </body>
        </html>
    );
}
